package io.joern.bytecode

object Defines {

  val GLOBAL_NAMESPACE_NAME = "PHPByteCode"

  val UNKNOWN_METHOD = "UNKNOWN_METHOD"

  val UNKNOWN_FUNCTION = "UNKNOWN_FUNCTION"

  val DYNAMIC_FUNCTION = "DYNAMIC_FUNCTION"

  val INTERNAL_FUNCTION = "INTERNAL_FUNCTION"

  val CONSTRUCTOR = "CONSTRUCTOR"

  val MULTIPLE_TARGETS = "MULTIPLE_TARGETS"

}
